<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.8.3">
]
>

<object class="weka.classifiers.rules.PART" name="__root__" version="3.8.3">
   <object class="boolean" name="debug" primitive="yes">false</object>
   <object array="yes" class="java.lang.String" name="options">
      <object class="java.lang.String" name="0">-M</object>
      <object class="java.lang.String" name="1">2</object>
      <object class="java.lang.String" name="2">-C</object>
      <object class="java.lang.String" name="3">0.25</object>
      <object class="java.lang.String" name="4">-Q</object>
      <object class="java.lang.String" name="5">1</object>
   </object>
</object>
